set(util_headers
  include/levk/util/async_queue.hpp
  include/levk/util/async_task.hpp
  include/levk/util/binary_file.hpp
  include/levk/util/bit_flags.hpp
  include/levk/util/bool.hpp
  include/levk/util/cli_opts.hpp
  include/levk/util/contiguous_storage.hpp
  include/levk/util/defer_queue.hpp
  include/levk/util/dyn_array.hpp
  include/levk/util/enum_array.hpp
  include/levk/util/enum_concept.hpp
  include/levk/util/enumerate.hpp
  include/levk/util/env.hpp
  include/levk/util/error.hpp
  include/levk/util/fixed_string.hpp
  include/levk/util/flex_array.hpp
  include/levk/util/hash_combine.hpp
  include/levk/util/id.hpp
  include/levk/util/logger.hpp
  include/levk/util/monotonic_map.hpp
  include/levk/util/not_null.hpp
  include/levk/util/nvec3.hpp
  include/levk/util/path_tree.hpp
  include/levk/util/pinned.hpp
  include/levk/util/ptr.hpp
  include/levk/util/signal.hpp
  include/levk/util/thread_pool.hpp
  include/levk/util/time.hpp
  include/levk/util/type_id.hpp
  include/levk/util/unique_task.hpp
  include/levk/util/unique.hpp
  include/levk/util/version.hpp
  include/levk/util/visitor.hpp
  include/levk/util/zip_ranges.hpp
)

set(window_headers
  include/levk/window/common.hpp
  include/levk/window/window_state.hpp
  include/levk/window/window.hpp
  include/levk/window/input.hpp
)

set(graphics_headers
  include/levk/graphics/camera.hpp
  include/levk/graphics/common.hpp
  include/levk/graphics/draw_list.hpp
  include/levk/graphics/drawable.hpp
  include/levk/graphics/geometry.hpp
  include/levk/graphics/image.hpp
  include/levk/graphics/lights.hpp
  include/levk/graphics/material.hpp
  include/levk/graphics/mesh.hpp
  include/levk/graphics/primitive.hpp
  include/levk/graphics/render_device.hpp
  include/levk/graphics/render_list.hpp
  include/levk/graphics/renderer.hpp
  include/levk/graphics/rgba.hpp
  include/levk/graphics/shader_buffer.hpp
  include/levk/graphics/shader_code.hpp
  include/levk/graphics/shader.hpp
  include/levk/graphics/skeleton.hpp
  include/levk/graphics/texture_atlas.hpp
  include/levk/graphics/texture_sampler.hpp
  include/levk/graphics/texture.hpp
  include/levk/graphics/transform_animation.hpp
)

set(imcpp_headers
  include/levk/imcpp/asset_inspector.hpp
  include/levk/imcpp/common.hpp
  include/levk/imcpp/drag_drop.hpp
  include/levk/imcpp/editor_window.hpp
  include/levk/imcpp/engine_status.hpp
  include/levk/imcpp/input_text.hpp
  include/levk/imcpp/inspector.hpp
  include/levk/imcpp/log_display.hpp
  include/levk/imcpp/reflector.hpp
  include/levk/imcpp/ring_buffer.hpp
  include/levk/imcpp/scene_graph.hpp
)

set(assets_headers
  include/levk/asset/asset_list_loader.hpp
  include/levk/asset/asset_list.hpp
  include/levk/asset/asset_provider.hpp
  include/levk/asset/asset_providers.hpp
  include/levk/asset/common.hpp
  include/levk/asset/font_provider.hpp
  include/levk/asset/material_provider.hpp
  include/levk/asset/mesh_provider.hpp
  include/levk/asset/shader_provider.hpp
  include/levk/asset/skeleton_provider.hpp
  include/levk/asset/texture_provider.hpp
)

set(vfs_headers
  include/levk/vfs/data_sink.hpp
  include/levk/vfs/data_source.hpp
  include/levk/vfs/disk_vfs.hpp
  include/levk/vfs/uri_monitor.hpp
)

set(io_headers
  include/levk/io/binding_map.hpp
  include/levk/io/component_factory.hpp
  include/levk/io/serializable.hpp
  include/levk/io/serializer.hpp
)

set(font_headers
  include/levk/font/ascii_font.hpp
  include/levk/font/common.hpp
  include/levk/font/font_glyph.hpp
  include/levk/font/font_library.hpp
  include/levk/font/glyph_slot.hpp
  include/levk/font/static_font_atlas.hpp
)

set(scene_headers
  include/levk/scene/component.hpp
  include/levk/scene/entity.hpp
  include/levk/scene/scene_manager.hpp
  include/levk/scene/scene.hpp
)

set(ui_headers
  include/levk/ui/primitive.hpp
  include/levk/ui/text.hpp
  include/levk/ui/view.hpp
)

set(levk_headers
  ${util_headers}
  ${impl_headers}
  ${window_headers}
  ${graphics_headers}
  ${imcpp_headers}
  ${assets_headers}
  ${vfs_headers}
  ${font_headers}
  ${scene_headers}
  ${ui_headers}

  include/levk/context.hpp
  include/levk/defines.hpp
  include/levk/engine.hpp
  include/levk/interpolator.hpp
  include/levk/node.hpp
  include/levk/rect.hpp
  include/levk/runtime.hpp
  include/levk/service.hpp
  include/levk/transform.hpp
  include/levk/uri.hpp
)
