name: ci
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init
        run: sudo apt update -yqq && sudo apt install -yqq ninja-build xorg-dev g++-11
      - name: configure gcc
        run: cmake -S . --preset=default -B build -DLEVK_USE_FREETYPE=OFF -DCMAKE_CXX_COMPILER=g++-11
      - name: configure clang
        run: cmake -S . --preset=ninja-clang -B clang -DLEVK_USE_FREETYPE=OFF
      - name: build gcc
        run: cmake --build build --config=Release
      - name: build clang
        run: cmake --build clang --config=Release
      - name: test
        run: cd build && ctest -C Release
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: cmake -S . --preset=vs22 -B build -DLEVK_USE_FREETYPE=OFF
      - name: build
        run: cmake --build build --config=Release
      - name: test
        run: cd build && ctest -C Release
